### ISSUE TITLE
Overview loading button continues to load

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#102]
### Basic information:

* OS (Android / iOS / both): Android Samsung galaxy alpha 4.4
* Version: 1.0.18 (1528815062)

### Issue description:

The loading button just keeps loading and loading forever

### Screenshots or mock-ups

![image 2018-06-13 15 43 20](https://user-images.githubusercontent.com/18598519/41354912-7ff146f6-6f20-11e8-80fc-fd2c40338750.jpg)

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Still not fixed on Kris' phone (Experia XA1 / Android 8.0.0)


![46aceae9-2719-4848-ab8e-85292770e8ac](https://user-images.githubusercontent.com/18598519/41534526-1f94fba8-72ff-11e8-8c22-4f7023d43074.jpg)


Not sure how to proceed here @jensneuber ?

**Comment by Kisgus** [comment]
Btw. Tested appcenter, but could not retrieve any information

**Comment by jensneuber** [comment]
Closed, since the underlaying error is the same as in https://github.com/trustlines-network/feedback/issues/133
