### ISSUE TITLE
Opening my own receive-payment link shows error

### ISSUE THREAD

**Issue by andfletcher** [trustlines-network/feedback#89]
### Basic information:

* OS (Android): 
* Version: 

### Issue description:
If i click on a link that i share to create a trusline with someone i am able to create a trustline with myself

**Comment by Kisgus** [comment]
Question @andfletcher can you actually go through the whole process of creating a trustline with yourself or rather entering the first step?

**Comment by andfletcher** [comment]
@Kisgus what do you mean with first step? If i share my Adresse with myself and i click on it my own Contact gets included within the trustlines overview.

**Comment by andfletcher** [comment]
@Kisgus do i need to be assigned to this? not sure what i am suppose to do.

**Comment by seichris** [comment]
I can still reproduce it.

Opening my onboarding link -> able to set trustlines agreement
Opening my own contact link -> able to add myself as a contact
Opening my own receive-payment link -> opens payment-amount screen, but error comes.

Trustlines App version: 1.0.18 (1531397023), Android 7.0, Xiaomi 5s

Can we block this in the app @jensneuber ? With an error screen saying "You cannot open your own trustlines link"?

**Comment by seichris** [comment]
### Solved

Opening my onboarding link
Opening my own contact link

### Not Solved
Opening my own receive-payment link -> opens payment-amount screen, but error comes.

**Comment by andfletcher** [comment]
@jensneuber @berndbohmeier is this still being worked on? I just checked and i still can add myself and create a trustline with myself.

**Comment by berndbohmeier** [comment]
This should be fixed in develop, can you please check and describe what is still broken?

**Comment by seichris** [comment]
Opening the link in the develop version (1.1.2-dev8 Android) freezes the app in a white screen.

**Comment by seichris** [comment]
Fixed in 1.1.2-dev9.

But screen looks ugly. Will fix with Julian.

![603627182-opt](https://user-images.githubusercontent.com/25006584/47422798-ca542580-d783-11e8-8d83-989d366d8b13.jpg)

**Comment by dakingha69** [comment]
@seichris the error should still occur when you share a link with a subject... PR https://github.com/trustlines-network/mobileapp/pull/340 should fix it. Will reopen and close it as soon as PR is merged.

**Comment by andfletcher** [comment]
Fixed
