### ISSUE TITLE
Fees displayed weird on Send ETH confirmation screen

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#99]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

See below picture

### Screenshots or mock-ups

![img_3504](https://user-images.githubusercontent.com/18598519/41354421-40aed4d2-6f1f-11e8-9ab2-6acb9fe616e1.png)

### Possible solution

If we cannot display fees anyway, lets just delete it and only include "view on etherscan" link

**Comment by krisnaer** [comment]
- OS (Android / iOS / both): Android
- Version: 8.0.0 

Could not reproduce this exact bug, but the "Max Fees" text field seems to adjust to the width of my screen. Please see attachments

![image](https://user-images.githubusercontent.com/29100596/41459169-052eabb0-7089-11e8-800e-a509d35749d7.png)

![image](https://user-images.githubusercontent.com/29100596/41459295-744de236-7089-11e8-8c26-a6150759b3a7.png)

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Tested and works on Android (Honor device), however still not fixed on iOS 5s, see picture

![img_3520](https://user-images.githubusercontent.com/18598519/41535264-fc10b94e-7301-11e8-8a67-55e995c9c4ed.png)

**Comment by Kisgus** [comment]
Another issue is clicking "view on etherscan" does not take you anywhere here. It should direct to the etherscan address of the recepient

**Comment by krisnaer** [comment]
@jensneuber Could the issue not just be solved by using two lines instead of one for "Max fees: 0.xxxx"? If so, I suggest doing this instead.

**Comment by jensneuber** [comment]
@krisnaer as in the last [screenshot](https://user-images.githubusercontent.com/18598519/41535264-fc10b94e-7301-11e8-8a67-55e995c9c4ed.png) or different?

**Comment by Kisgus** [comment]
I would 1) Have 2 lines & 2) middle-center both lines

**Comment by jensneuber** [comment]
Input beyond the networks decimal sis prevented now

**Comment by Kisgus** [comment]
Okay, could we fix this via "live-coding" session @jensneuber ? :)

**Comment by seichris** [comment]
Looks good now.
